# base image
FROM node:10.15.3

# run on port 3000
EXPOSE 3000

# set working directory
RUN mkdir -p /var/app/
WORKDIR /var/app/

# copy config files
COPY config/ config/

# copy public assets
COPY public/ public/

# copy scripts generated by `create-elm-app`
# This won't exist if `create-elm-app` hasn't been ejected.
COPY scripts/ scripts/

# npm install dependencies for
COPY package.json .
COPY package-lock.json .
RUN npm install

# copy Elm source files
# TODO: these should be symlinked for development
COPY src/ src/

# Compile elm src
COPY elm.json .
RUN npm run make src/Main.elm

# run the server
ENV ELM_DEBUGGER=false
CMD ["npm", "run", "start"]
