-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PokerApi.InputObject exposing (..)


placeholder : String
placeholder =
    ""
