-- Do not manually edit this file, it was auto-generated by Graphql
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Object exposing (Estimate(..), Game(..), Round(..), Session(..), User(..))


type Estimate
    = Estimate


type Game
    = Game


type Round
    = Round


type Session
    = Session


type User
    = User
