-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Object exposing (..)


type Estimate
    = Estimate


type Game
    = Game


type Round
    = Round


type Session
    = Session


type User
    = User
