-- Do not manually edit this file, it was auto-generated by Graphql
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Union exposing (placeholder)


placeholder : String
placeholder =
    ""
