-- Do not manually edit this file, it was auto-generated by Graphql
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Object.Estimate exposing (amount, id, selection, user)

import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PokerApi.InputObject
import PokerApi.Interface
import PokerApi.Object
import PokerApi.Scalar
import PokerApi.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PokerApi.Object.Estimate
selection constructor =
    Object.selection constructor


amount : Field (Maybe String) PokerApi.Object.Estimate
amount =
    Object.fieldDecoder "amount" [] (Decode.string |> Decode.nullable)


id : Field PokerApi.Scalar.Id PokerApi.Object.Estimate
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map String.fromFloat, Decode.int |> Decode.map String.fromInt ] |> Decode.map PokerApi.Scalar.Id)


user : SelectionSet decodesTo PokerApi.Object.User -> Field decodesTo PokerApi.Object.Estimate
user object =
    Object.selectionField "user" [] object identity
