-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Object.Estimate exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PokerApi.InputObject
import PokerApi.Interface
import PokerApi.Object
import PokerApi.Scalar
import PokerApi.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PokerApi.Object.Estimate
selection constructor =
    Object.selection constructor


amount : Field (Maybe String) PokerApi.Object.Estimate
amount =
    Object.fieldDecoder "amount" [] (Decode.string |> Decode.nullable)


id : Field PokerApi.Scalar.Id PokerApi.Object.Estimate
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map PokerApi.Scalar.Id)


user : SelectionSet decodesTo PokerApi.Object.User -> Field decodesTo PokerApi.Object.Estimate
user object =
    Object.selectionField "user" [] object identity
