-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Object.Game exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PokerApi.InputObject
import PokerApi.Interface
import PokerApi.Object
import PokerApi.Scalar
import PokerApi.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PokerApi.Object.Game
selection constructor =
    Object.selection constructor


currentRound : SelectionSet decodesTo PokerApi.Object.Round -> Field (Maybe decodesTo) PokerApi.Object.Game
currentRound object =
    Object.selectionField "currentRound" [] object (identity >> Decode.nullable)


id : Field PokerApi.Scalar.Id PokerApi.Object.Game
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map PokerApi.Scalar.Id)


name : Field String PokerApi.Object.Game
name =
    Object.fieldDecoder "name" [] Decode.string


players : SelectionSet decodesTo PokerApi.Object.User -> Field (Maybe (List (Maybe decodesTo))) PokerApi.Object.Game
players object =
    Object.selectionField "players" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


rounds : SelectionSet decodesTo PokerApi.Object.Round -> Field (List (Maybe decodesTo)) PokerApi.Object.Game
rounds object =
    Object.selectionField "rounds" [] object (identity >> Decode.nullable >> Decode.list)


status : Field String PokerApi.Object.Game
status =
    Object.fieldDecoder "status" [] Decode.string
