-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Object.Round exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PokerApi.InputObject
import PokerApi.Interface
import PokerApi.Object
import PokerApi.Scalar
import PokerApi.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PokerApi.Object.Round
selection constructor =
    Object.selection constructor


estimates : SelectionSet decodesTo PokerApi.Object.Estimate -> Field (Maybe (List (Maybe decodesTo))) PokerApi.Object.Round
estimates object =
    Object.selectionField "estimates" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


game : SelectionSet decodesTo PokerApi.Object.Game -> Field decodesTo PokerApi.Object.Round
game object =
    Object.selectionField "game" [] object identity


id : Field (Maybe PokerApi.Scalar.Id) PokerApi.Object.Round
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map PokerApi.Scalar.Id |> Decode.nullable)


status : Field String PokerApi.Object.Round
status =
    Object.fieldDecoder "status" [] Decode.string
