-- Do not manually edit this file, it was auto-generated by Graphql
-- https://github.com/dillonkearns/graphqelm


module PokerApi.Object.Round exposing (estimates, game, id, selection, status)

import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PokerApi.InputObject
import PokerApi.Interface
import PokerApi.Object
import PokerApi.Scalar
import PokerApi.Union


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) PokerApi.Object.Round
selection constructor =
    Object.selection constructor


estimates : SelectionSet decodesTo PokerApi.Object.Estimate -> Field (List decodesTo) PokerApi.Object.Round
estimates object =
    Object.selectionField "estimates" [] object (identity >> Decode.list)


game : SelectionSet decodesTo PokerApi.Object.Game -> Field decodesTo PokerApi.Object.Round
game object =
    Object.selectionField "game" [] object identity


id : Field (Maybe PokerApi.Scalar.Id) PokerApi.Object.Round
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map String.fromFloat, Decode.int |> Decode.map String.fromInt ] |> Decode.map PokerApi.Scalar.Id |> Decode.nullable)


status : Field String PokerApi.Object.Round
status =
    Object.fieldDecoder "status" [] Decode.string
